export const AstronautData = [
    {
        "id": 1,
        "name": "Ravish Malhotra",
        "birthdate": "25 December 1943",
        "age": 80,
        "birthplace": "Lahore, Punjab, British India",
        "almaMater": "National Defence Academy",
        "occupation": "Test Pilot, Air Commodore in the Indian Air Force",
        "timeInSpace": "None (Trained as backup for Soyuz T-11)",
        "missions": "Soyuz T-11 (Backup)",
        link: "https://en.wikipedia.org/wiki/Mylswamy_Annadurai",
        "spouse": "Mira Malhotra",
        "children": 2,
        "notableAchievements": "Trained as the backup for Rakesh Sharma, who was the first Indian in space.",
        "quote": "\"I was disappointed, but you accept it, and move on with the mission.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Wing_Commander_Ravish_Malhotra.jpg/330px-Wing_Commander_Ravish_Malhotra.jpg"
      },
      {
        "id": 2,
        "name": "Kalpana Chawla",
        "birthdate": "17 March 1962",
        "age": "Deceased (Died on 1 February 2003)",
        "birthplace": "Karnal, Haryana, India",
        "almaMater": "Punjab Engineering College, University of Texas at Arlington, University of Colorado Boulder",
        "occupation": "Astronaut, Aerospace Engineer",
        "timeInSpace": "31d 14h 54m",
        "missions": ["STS-87", "STS-107"],
        link: "https://en.wikipedia.org/wiki/Kalpana_Chawla#:~:text=Chawla%20was%20the%20first%20Indian,and%2016%20hours)%20in%20space.",
        "spouse": "Jean-Pierre Harrison",
        "children": "None",
        "notableAchievements": "First woman of Indian origin in space. Lost her life in the Space Shuttle Columbia disaster.",
        "quote": "\"The journey matters as much as the goal.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Kalpana_Chawla%2C_NASA_photo_portrait_in_orange_suit.jpg/330px-Kalpana_Chawla%2C_NASA_photo_portrait_in_orange_suit.jpg"
      },
      {
        "id": 3,
        "name": "Rakesh Sharma",
        "birthdate": "13 January 1949",
        "age": 75,
        "birthplace": "Patiala, Punjab, India",
        "almaMater": "National Defence Academy, Air Force Academy",
        "occupation": "Fighter pilot at IAF, Research Cosmonaut at ISRO, Test pilot at HAL",
        "timeInSpace": "7d 21h 40m",
        "missions": ["Soyuz T-11/T-10"],
        link: "https://en.wikipedia.org/wiki/Mylswamy_Annadurai",
        "spouse": "Madhu Sharma",
        "children": 2,
        "notableAchievements": "First Indian citizen to travel to space.",
        "quote": "\"Sare Jahan Se Accha\" - describing how India looked from space.",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Rakesh_sharma.jpg/330px-Rakesh_sharma.jpg"
      },
      {
        "id": 4,
        "name": "Lalithambika V.R.",
        "birthdate": "1957",
        "age": 67,
        "birthplace": "Kerala, India",
        "almaMater": "College of Engineering, Thiruvananthapuram",
        "occupation": "Scientist, Engineer, Director of Human Spaceflight Programme at ISRO",
        "timeInSpace": "None",
        "missions": "Gaganyaan (Director)",
        link: "https://en.wikipedia.org/wiki/V._R._Lalithambika",
        "spouse": "Information not publicly available",
        "children": "Information not publicly available",
        "notableAchievements": "Head of ISRO’s Human Spaceflight Programme, contributing to India's manned mission to space.",
        "quote": "\"When you dream of something big, you can achieve it.\"",
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxCQqt66CTDx6d9NXK-h3OjecddVpNoBBt5A&usqp=CAU"
      },
      {
        "id": 5,
        "name": "Ritu Karidhal",
        "birthdate": "13 April 1975",
        "age": 49,
        "birthplace": "Lucknow, Uttar Pradesh, India",
        "almaMater": "University of Lucknow, Indian Institute of Science, Bangalore",
        "occupation": "Aerospace Engineer, Scientist at ISRO",
        "timeInSpace": "None",
        "missions": ["Mangalyaan (Mars Orbiter Mission)", "Chandrayaan-2"],
        link: "https://en.wikipedia.org/wiki/Ritu_Karidhal",
        "spouse": "Information not publicly available",
        "children": "Information not publicly available",
        "notableAchievements": "Deputy Operations Director for Mangalyaan, India's Mars Orbiter Mission.",
        "quote": "\"Space is the future, and India's role in space is essential for our country's growth.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Ritu_Karidal_at_ISRO.jpg/330px-Ritu_Karidal_at_ISRO.jpg"
      },
      {
        "id": 6,
        "name": "Sunita Williams",
        "birthdate": "19 September 1965",
        "age": 58,
        "birthplace": "Euclid, Ohio, United States",
        "almaMater": "United States Naval Academy, Florida Institute of Technology",
        "occupation": "Astronaut, Naval Officer",
        "timeInSpace": "322d 22h 45m",
        "missions": ["STS-116", "STS-117", "Expedition 14", "Expedition 15", "Expedition 32", "Expedition 33"],
        link: "https://en.wikipedia.org/wiki/Sunita_Williams",
        "spouse": "Michael J. Williams",
        "children": "None",
        "notableAchievements": "Holds the record for the longest single spaceflight by a woman.",
        "quote": "\"If you don’t dream big, you’re not going to get there.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Sunita_Williams.jpg/330px-Sunita_Williams.jpg"
      },
      {
        "id": 7,
        "name": "Prasanth Nair",
        "birthdate": "26 August 1976",
        "age": 47,
        "birthplace": "Palakkad, Kerala, India",
        "almaMater": "NSS College of Engineering, United States Staff College",
        "occupation": "Test pilot, Astronaut candidate",
        "timeInSpace": "Scheduled for Gaganyaan mission",
        "missions": "Gaganyaan (scheduled)",
        link: "https://en.wikipedia.org/wiki/Prasanth_Nair",
        "spouse": "Lena",
        "children": "Not publicly known",
        "notableAchievements": "Commander of the Gaganyaan mission, qualified flight instructor",
        "quote": "Not publicly known",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Group_Captain_Prasanth_Balakrishnan_Nair.jpg/330px-Group_Captain_Prasanth_Balakrishnan_Nair.jpg"
      }
      ,
      {
        "id": 8,
        "name": "Vyommitra",
        "birthdate": "Unmanned",
        "age": "N/A",
        "birthplace": "ISRO, India",
        "almaMater": "ISRO",
        "occupation": "Humanoid Robot",
        "timeInSpace": "Planned for Gaganyaan mission",
        "missions": ["Gaganyaan (Planned)"],
        link: "https://en.wikipedia.org/wiki/Vyommitra",
        "spouse": "None",
        "children": "None",
        "notableAchievements": "First humanoid robot developed by ISRO for unmanned space missions.",
        "quote": "\"Hello, I am Vyommitra, the first Indian humanoid robot designed for space missions.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Vyommitra_%28Space_friend%29%2C_ISRO.jpg/330px-Vyommitra_%28Space_friend%29%2C_ISRO.jpg"
      },
      {
        "id": 9,
        "name": "Shubhanshu Shukla",
        "birthdate": "10 October 1985",
        "age": 38,
        "birthplace": "Lucknow, Uttar Pradesh, India",
        "almaMater": "National Defence Academy",
        "occupation": "Test pilot, Astronaut candidate",
        "timeInSpace": "Scheduled for November 2024",
        link: "https://en.wikipedia.org/wiki/Shubhanshu_Shukla",
        "spouse": "Not publicly known",
        "children": "Not publicly known",
        "notableAchievements": "Selected as one of the four astronaut candidates for India's first crewed space mission.",
        "quote": "Not publicly known",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Wing_Commander_Shubhanshu_Shukla.jpg/330px-Wing_Commander_Shubhanshu_Shukla.jpg"
      },
      
      {
        "id": 10,
        "name": "Tessy Thomas",
        "birthdate": "1963",
        "age": 61,
        "birthplace": "Alappuzha, Kerala, India",
        "almaMater": "College of Engineering, Thiruvananthapuram, Defence Institute of Advanced Technology",
        "occupation": "Scientist, Director General of Aeronautical Systems at DRDO",
        "timeInSpace": "None",
        "missions": ["AGNI-V", "AGNI-IV"],
        link: "https://en.wikipedia.org/wiki/Tessy_Thomas",
        "spouse": "Sarbani Das",
        "children": 1,
        "notableAchievements": "Known as the 'Missile Woman of India' for her work on AGNI missiles.",
        "quote": "\"Missiles are not just machines; they are a symbol of our nation's strength.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Tessy_thomas.png/330px-Tessy_thomas.png"
      },
      {
        "id": 11,
        "name": "Satish Dhawan",
        "birthdate": "25 September 1920",
        "age": "Deceased (Died on 3 January 2002)",
        "birthplace": "Srinagar, Jammu and Kashmir, India",
        "almaMater": "University of the Punjab, University of Minnesota, Caltech",
        "occupation": "Space Scientist, Former Chairman of ISRO",
        "timeInSpace": "None",
        "missions": ["SLV-3", "Rohini"],
        link: "https://en.wikipedia.org/wiki/Satish_Dhawan",
        "spouse": "Nalini Dhawan",
        "children": 2,
        "notableAchievements": "Considered the architect of the Indian space program. ISRO's space center in Sriharikota is named after him.",
        "quote": "\"India’s space journey is a testament to what vision and perseverance can achieve.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/en/3/3d/Satish_Dhawan.jpg"
      },
      {
        "id": 12,
        "name": "K. Sivan",
        "birthdate": "14 April 1957",
        "age": 67,
        "birthplace": "Mela Sarakkalvilai, Tamil Nadu, India",
        "almaMater": "Madras Institute of Technology, Indian Institute of Science, Indian Institute of Technology Bombay",
        "occupation": "Space Scientist, Former Chairman of ISRO",
        "timeInSpace": "None",
        "missions": ["Chandrayaan-2", "Gaganyaan", "Mars Orbiter Mission"],
        link: "https://en.wikipedia.org/wiki/K._Sivan#:~:text=Sivan%20Kailasavadivu%20(born%2014%20April,(ISRO)%20and%20Space%20Commission.",
        "spouse": "Malathi Sivan",
        "children": 2,
        "notableAchievements": "Led key missions like Chandrayaan-2 and the Mars Orbiter Mission, earning the nickname 'Rocket Man of India.'",
        "quote": "\"Failure is not an option when you have the weight of a nation's dreams on your shoulders.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/K._Sivan.jpg/330px-K._Sivan.jpg"
      },
      {
        "id": 13,
        "name": "G. Madhavan Nair",
        "birthdate": "31 October 1943",
        "age": 80,
        "birthplace": "Nedumangad, Kerala, India",
        "almaMater": "College of Engineering, Thiruvananthapuram",
        "occupation": "Space Scientist, Former Chairman of ISRO",
        "timeInSpace": "None",
        "missions": ["Chandrayaan-1", "GSAT", "PSLV"],
        link: "https://en.wikipedia.org/wiki/G._Madhavan_Nair",
        "spouse": "Unknown",
        "children": 2,
        "notableAchievements": "Led the Chandrayaan-1 mission, India's first mission to the Moon.",
        "quote": "\"Exploring space is not just about science; it's about making history.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/89/APJwithNair.JPG"
      },
      
      
      {
        "id": 14,
        "name": "Udupi Ramachandra Rao",
        "birthdate": "10 March 1932",
        "age": "Deceased (Died on 24 July 2017)",
        "birthplace": "Adamaru, Karnataka, India",
        "almaMater": "Banaras Hindu University, MIT",
        "occupation": "Space Scientist, Former Chairman of ISRO",
        "timeInSpace": "None",
        "missions": ["Aryabhata", "INSAT", "SLV-3"],
        link: "https://en.wikipedia.org/wiki/Udupi_Ramachandra_Rao",
        "spouse": "Malathi Rao",
        "children": 2,
        "notableAchievements": "Played a crucial role in the development of India's first satellite, Aryabhata, and was awarded the Padma Bhushan and Padma Vibhushan.",
        "quote": "\"The sky is not the limit, it is just the beginning.\"",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/21/U_R_Rao_%28cropped%29.jpg"
      },
      {
        "id": 15,
        "name": "Mylswamy Annadurai",
        "birthdate": "2 July 1958",
        "age": 66,
        "birthplace": "Kothavadi, Tamil Nadu, India",
        "almaMater": "Government College of Technology, Coimbatore, PSG College of Technology, Coimbatore",
        "occupation": "Space Scientist, Project Director of Chandrayaan-1 and Mangalyaan",
        "timeInSpace": "None",
        "missions": ["Chandrayaan-1", "Mars Orbiter Mission"],
        
        "spouse": "Vasanthi Annadurai",
        "children": 2,
        "notableAchievements": "Known as the 'Moon Man of India,' he led the Chandrayaan-1 and Mars Orbiter Mission.",
        "quote": "\"Reaching for the stars begins with the courage to dream.\"",
        link: "https://en.wikipedia.org/wiki/Mylswamy_Annadurai",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Mylswamy_Annadurai.jpg/330px-Mylswamy_Annadurai.jpg"
      },
      {
        "id": 16,
        "name": "K. Radhakrishnan",
        "birthdate": "29 August 1949",
        "age": 74,
        "birthplace": "Irinjalakuda, Kerala, India",
        "almaMater": "Indian Institute of Technology Kharagpur, Indian Institute of Management Bangalore",
        "occupation": "Space Scientist, Former Chairman of ISRO",
        "timeInSpace": "None",
        "missions": ["Mars Orbiter Mission", "GSAT", "Chandrayaan-2"],
        
        "spouse": "Padmini Radhakrishnan",
        "children": 1,
        "notableAchievements": "Oversaw India's first successful mission to Mars, the Mars Orbiter Mission (Mangalyaan).",
        "quote": "\"Success is a journey, not a destination; Mangalyaan was one step in that journey.\"",
        link: "https://en.wikipedia.org/wiki/Koppillil_Radhakrishnan",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/K-Radhakrishnan-2014.jpg/375px-K-Radhakrishnan-2014.jpg"
      }
      
      
      
      
           
      
      
      
      
      
];