export const satelliteData = [
  {
    id: 1,
    name: "Aryabhata",
    missionType: "Astrophysics",
    operator: "ISRO",
    launchDate: "19 April 1975",
    launchMass: "360 kg (790 lb)",
    power: "46 W",
    launchVehicle: "Kosmos-3M",
    launchSite: "Kapustin Yar 107/2",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Low Earth",
      perigeeAltitude: "563 km (350 mi)",
      apogeeAltitude: "619 km (385 mi)",
      inclination: "50.7 degrees",
      period: "96.46 minutes"
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Aryabhata_Satellite.jpg/405px-Aryabhata_Satellite.jpg",
    description: "Aryabhata was India's first satellite, launched on 19 April 1975. Built by ISRO and launched by the Soviet Union as part of the Soviet Interkosmos programme, Aryabhata was designed to conduct experiments in X-ray astronomy, aeronomics, and solar physics. The spacecraft was a 26-sided polyhedron with solar cells on all faces except the top and bottom. Power failure halted experiments after four days, and all signals were lost after five days. The satellite remained active until March 1981 and re-entered Earth's atmosphere on 10 February 1992 due to orbital decay.",
    link: "https://en.wikipedia.org/wiki/Aryabhata_(satellite)",
    category: "Mission failure", // Aryabhata had a mission failure due to power loss
  },
  
  {
    id: 2,
    name: "GSAT-30",
    missionType: "Communications",
    operator: "ISRO",
    launchDate: "16 January 2020",
    launchMass: "3,357 kg (7,401 lb)",
    power: "6000 watts",
    launchVehicle: "Ariane 5 ECA (VA-251)",
    launchSite: "Kourou, ELA-3",
    orbit: {
      referenceSystem: "Geocentric orbit",
      regime: "Geostationary orbit",
      longitude: "83.0° East",
    },
    transponders: {
      C_band: 12,
      Ku_band: 12,
    },
    coverageArea: "Asia, Australia",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Render_of_GSAT-30_spacecraft_in_deployed_configuration.png/450px-Render_of_GSAT-30_spacecraft_in_deployed_configuration.png",
    description: "GSAT-30 is a communication satellite developed by ISRO. It enhances telecommunication and broadcasting services for Asia and Australia. The satellite is equipped with C-band and Ku-band transponders, providing a wide range of communication services including television broadcasting and telecommunication.",
    link: "https://en.wikipedia.org/wiki/GSAT-30",
    category: "Geostationary Orbit", // GSAT-30 is in geostationary orbit
  },
  
  {
    id: 3,
    name: "GSAT-31",
    missionType: "Communication",
    operator: "ISRO",
    cosparId: "2019-007B",
    satcatNo: "44035",
    missionDuration: "Planned: 15 years",
    elapsedDuration: "5 years, 6 months, 3 days",
    spacecraftProperties: {
      bus: "I-2K",
      manufacturer: "ISRO Satellite Centre",
      spaceApplicationsCentre: "Space Applications Centre",
    },
    launchMass: "2,536 kg (5,591 lb)",
    power: "Solar arrays, batteries",
    launchDate: "6 February 2019",
    launchVehicle: "Ariane 5 VCA",
    launchSite: "Kourou ELA-3",
    contractor: "Arianespace",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      slot: "82.95°E",
      initialSlot: "48°E (Feb to Sept 2019)",
    },
    transponders: {
      band: "Ku",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/GSAT-31_render_02.png/390px-GSAT-31_render_02.png",
    description: "GSAT-31 is a communication satellite designed to extend ISRO's communication capabilities. It features Ku-band transponders and provides services such as direct-to-home (DTH) broadcasting and broadband connectivity. The satellite has a high capacity and is aimed at improving communication infrastructure across India.",
    link: "https://en.wikipedia.org/wiki/GSAT-31",
    category: "Geosynchronous Orbit", // GSAT-31 is in geosynchronous orbit
  },
  
  {
    id: 4,
    name: "GSAT-11",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "4 December 2018",
    launchMass: "5,854 kg (12,906 lb)",
    power: "13.6 kilowatts",
    launchVehicle: "Ariane 5 VA246",
    launchSite: "Guiana Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "74° East",
    },
    transponders: {
      Ku_band: 32,
      Ka_band: 8,
      bandwidth: "16 Gbps",
    },
    coverageArea: "India and surrounding regions",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/GSAT-11_in_cleanroom_01.jpg/390px-GSAT-11_in_cleanroom_01.jpg",
    description: "GSAT-11 is a high-throughput communication satellite launched by ISRO. It supports a variety of communication services including broadband, telecommunication, and broadcasting. The satellite features an advanced transponder system that includes both Ku-band and Ka-band transponders, providing high-speed data transmission and coverage across India.",
    link: "https://en.wikipedia.org/wiki/GSAT-11",
    category: "Geostationary Orbit", // GSAT-11 is in geostationary orbit
  },
  
  {
    id: 5,
    name: "INSAT-1B",
    missionType: "Communications",
    operator: "INSAT",
    cosparId: "1983-089B",
    satcatNo: "14318",
    missionDuration: "7 years",
    launchDate: "30 August 1983",
    launchVehicle: "Space Shuttle Challenger STS-8 / PAM-D",
    launchSite: "Kennedy LC-39A",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      initialLongitude: "74° East",
      finalLongitude: "93° East",
    },
    transponders: {
      C_band: 12,
      S_band: 3,
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Insat-1B.jpg/390px-Insat-1B.jpg",
    description: "INSAT-1B was a communication satellite in the INSAT series, launched by ISRO. It was designed to provide telecommunication, television broadcasting, and meteorological services. The satellite's C-band and S-band transponders enabled it to serve a variety of communication needs across India and surrounding regions.",
    link: "https://en.wikipedia.org/wiki/INSAT-1B",
    category: "Crewed spacecraft", // INSAT-1B was launched aboard the crewed Space Shuttle Challenger
  },
  
  {
    id: 6,
    name: "INSAT-2B",
    missionType: "Telecommunication and Meteorological Observation",
    operator: "INSAT",
    launchDate: "23 July 1993",
    launchMass: "1,906 kg (4,202 lb)",
    power: "1000 watts",
    launchVehicle: "Ariane-4",
    launchSite: "Kourou, French Guiana",
    contractor: "Arianespace",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "93.5° East",
    },
    transponders: {
      SAR: "Search and Rescue",
      dataRelay: "Data Collection",
      radiometer: "Very High-resolution Radiometer",
    },
    coverageArea: "Indian subcontinent",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1glkB-nqvE48gG0XunQk05ONYq1tHqn3Nmo9UGhs&usqp=CAE&s",
    description: "INSAT-2B was the second satellite in the INSAT 2 Series, launched for telecommunication and meteorological observation. It was placed in a geostationary orbit at 93.5° East longitude. The satellite carried a Very High-resolution Radiometer (VHRR) capable of operating in multiple modes, a Data Collection System (DCS) for environmental information, and a Satellite Aided Search and Rescue (SASAR) system for emergency support.",
    link: "https://en.wikipedia.org/wiki/INSAT-2B",
    category: "Telecommunication and Meteorological Observation", // INSAT-2B had this dual purpose
  },
  {
    id: 7,
    name: "RISAT-2",
    missionType: "Radar Imaging",
    operator: "ISRO",
    launchDate: "20 April 2009",
    launchMass: "300 kg (660 lb)",
    power: "430 watts",
    launchVehicle: "PSLV-C12",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Low Earth",
      perigeeAltitude: "400 km (250 mi)",
      apogeeAltitude: "600 km (370 mi)",
      inclination: "41 degrees",
      period: "90 minutes"
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/RISAT-2BR1_with_its_Radial_Rib_Antenna_deployed.png/290px-RISAT-2BR1_with_its_Radial_Rib_Antenna_deployed.png",
    description: "RISAT-2 is an Indian radar reconnaissance satellite built by ISRO. It is intended to enhance India's capabilities in surveillance, reconnaissance, and disaster management. The satellite carries a synthetic-aperture radar (SAR) that can provide all-weather surveillance capabilities.",
    link: "https://en.wikipedia.org/wiki/RISAT-2",
    category: "Low Earth Orbit", // RISAT-2 operates in low Earth orbit
  },

  {
    id: 8,
    name: "INSAT-3D",
    missionType: "Meteorology",
    operator: "ISRO",
    launchDate: "26 July 2013",
    launchMass: "2,060 kg (4,540 lb)",
    power: "1,100 watts",
    launchVehicle: "Ariane 5 VA214",
    launchSite: "Guiana Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "82° East",
    },
    payload: {
      imager: "6-channel multispectral imager",
      sounder: "19-channel sounder",
      SAR: "Search and Rescue Transponder",
    },
    image: "https://www.eoportal.org/api/cms/documents/163813/2019625/INSAT3D_Auto14.jpeg",
    description: "INSAT-3D is an advanced meteorological satellite designed by ISRO to improve weather forecasting and disaster warning capabilities. The satellite is equipped with a 6-channel imager and a 19-channel sounder for accurate weather observations, as well as a search and rescue transponder.",
    link: "https://en.wikipedia.org/wiki/INSAT-3D",
    category: "Geostationary Orbit", // INSAT-3D operates in geostationary orbit
  },
  {
    id: 9,
    name: "GSAT-6A",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "29 March 2018",
    launchMass: "2,140 kg (4,718 lb)",
    power: "3,000 watts",
    launchVehicle: "GSLV Mk II",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "83° East",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/GSAT-6A_Undergoing_Acoustic_Test.jpg/390px-GSAT-6A_Undergoing_Acoustic_Test.jpg",
    description: "GSAT-6A was a communication satellite launched by ISRO. Shortly after its launch, communication with the satellite was lost, leading to mission failure. GSAT-6A was intended to provide mobile communication through multi-beam coverage.",
    link: "https://en.wikipedia.org/wiki/GSAT-6A",
    category: "Mission failure", // The satellite mission was categorized as a failure due to loss of communication.
  },
  {
    id: 10,
    name: "Chandrayaan-2",
    missionType: "Lunar Exploration",
    operator: "ISRO",
    launchDate: "22 July 2019",
    launchMass: "3,850 kg (8,490 lb)",
    power: "1,000 watts",
    launchVehicle: "GSLV Mk III",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Selenocentric",
      regime: "Polar orbit around the Moon",
      periapsis: "100 km (62 mi)",
      apoapsis: "100 km (62 mi)",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/GSLV_Mk_III_M1%2C_Chandrayaan-2_-_Vikram_lander_mounted_on_top_of_orbiter.jpg/390px-GSLV_Mk_III_M1%2C_Chandrayaan-2_-_Vikram_lander_mounted_on_top_of_orbiter.jpg",
    description: "Chandrayaan-2 was India's second lunar exploration mission aimed at exploring the Moon's south pole. It included an orbiter, a lander named Vikram, and a rover named Pragyan. The mission's orbiter continues to function, providing valuable data.",
    link: "https://en.wikipedia.org/wiki/Chandrayaan-2",
    category: "Extra-terrestrial missions", // Chandrayaan-2 was an extra-terrestrial mission aimed at lunar exploration.
  },
  {
    id: 11,
    name: "GSAT-9 (South Asia Satellite)",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "5 May 2017",
    launchMass: "2,230 kg (4,920 lb)",
    power: "3,500 watts",
    launchVehicle: "GSLV Mk II",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geosynchronous",
      longitude: "48° East",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/GSAT-9_Deployed.png/1280px-GSAT-9_Deployed.png",
    description: "GSAT-9, also known as the South Asia Satellite, was launched to provide communication services to countries in South Asia. The satellite was placed in a geosynchronous orbit and supports various communication and broadcasting applications.",
    link: "https://en.wikipedia.org/wiki/GSAT-9",
    category: "Geosynchronous Orbit", // GSAT-9 operates in a geosynchronous orbit.
  },
  {
    id: 12,
    name: "INSAT-4A",
    missionType: "Communication",
    operator: "INSAT",
    launchDate: "22 December 2005",
    launchMass: "3,080 kg (6,790 lb)",
    power: "6,000 watts",
    launchVehicle: "Ariane 5 ECA",
    launchSite: "Guiana Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "83° East",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Render_of_INSAT-4A_spacecraft_in_deployed_configuration.jpg/390px-Render_of_INSAT-4A_spacecraft_in_deployed_configuration.jpg",
    description: "INSAT-4A was a communication satellite launched by ISRO as part of the INSAT series. It provided direct-to-home (DTH) television services and other telecommunication services across India. The satellite was placed in a geostationary orbit.",
    link: "https://en.wikipedia.org/wiki/INSAT-4A",
    category: "Geostationary Orbit", // INSAT-4A operates in a geostationary orbit.
  },
  {
    id: 13,
    name: "Gaganyaan",
    missionType: "Human Spaceflight",
    operator: "ISRO",
    launchDate: "Planned: 2024",
    launchMass: "Not specified",
    power: "Not specified",
    launchVehicle: "GSLV Mk III",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Low Earth",
      periapsis: "300 km (190 mi)",
      apoapsis: "400 km (250 mi)",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Gaganyaan_crewed_spacecraft_in_deployed_twin_solar_panel_configuration.png/450px-Gaganyaan_crewed_spacecraft_in_deployed_twin_solar_panel_configuration.png",
    description: "Gaganyaan is an Indian crewed spaceflight mission planned by ISRO. It aims to send a crew of Indian astronauts to low Earth orbit and bring them back safely. The mission is a major step in India's human space exploration program.",
    link: "https://en.wikipedia.org/wiki/Gaganyaan",
    category: "Crewed spacecraft", // Gaganyaan is India's first planned crewed spacecraft.
  },
  {
    id: 14,
    name: "INSAT-4C",
    missionType: "Communication",
    operator: "INSAT",
    launchDate: "10 July 2006",
    launchMass: "2,168 kg (4,779 lb)",
    power: "5,500 watts",
    launchVehicle: "GSLV Mk II",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "74° East",
    },
    image: "https://space.skyrocket.de/img_sat/insat-4c__1.jpg",
    description: "INSAT-4C was a communication satellite launched by ISRO, but the mission failed when the GSLV rocket malfunctioned shortly after liftoff. The satellite was intended to provide direct-to-home television services but was lost due to the launch vehicle's failure.",
    link: "https://en.wikipedia.org/wiki/INSAT-4C",
    category: "Mission failure", // The mission failed due to a launch vehicle malfunction.
  },
  {
    id: 15,
    name: "Mangalyaan (Mars Orbiter Mission)",
    missionType: "Mars Exploration",
    operator: "ISRO",
    launchDate: "5 November 2013",
    launchMass: "1,337 kg (2,948 lb)",
    power: "840 watts",
    launchVehicle: "PSLV-XL",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Areocentric",
      regime: "Mars orbit",
      periapsis: "365.3 km (227 mi)",
      apoapsis: "80,000 km (50,000 mi)",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mars_Orbiter_Mission_Over_Mars_%2815237158879%29.jpg/1024px-Mars_Orbiter_Mission_Over_Mars_%2815237158879%29.jpg",
    description: "Mangalyaan, also known as the Mars Orbiter Mission (MOM), was India's first interplanetary mission. Launched by ISRO, it successfully entered Mars orbit on 24 September 2014. The mission aimed to explore the Martian surface, morphology, atmosphere, and mineralogy.",
    link: "https://en.wikipedia.org/wiki/Mars_Orbiter_Mission",
    category: "Extra-terrestrial missions", // Mangalyaan was an interplanetary mission to Mars.
  },
  {
    id: 16,
    name: "GSAT-10",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "29 September 2012",
    launchMass: "3,400 kg (7,500 lb)",
    power: "6,000 watts",
    launchVehicle: "Ariane 5 ECA",
    launchSite: "Guiana Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geosynchronous",
      longitude: "83° East",
    },
    image: "https://sky-brokers.com/wp-content/uploads/2021/01/EuropeStar-satellite-in-orbit-950x745.jpeg",
    description: "GSAT-10 is a communication satellite launched by ISRO to enhance telecommunication, television broadcasting, and satellite-based navigation. It was placed in a geosynchronous orbit and has a mission life of 15 years.",
    link: "https://en.wikipedia.org/wiki/GSAT-10",
    category: "Geosynchronous Orbit", // GSAT-10 operates in a geosynchronous orbit.
  },
  {
    id: 17,
    name: "GSAT-16",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "7 December 2014",
    launchMass: "3,180 kg (7,010 lb)",
    power: "6,800 watts",
    launchVehicle: "Ariane 5 ECA",
    launchSite: "Guiana Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "55° East",
    },
    image: "https://space.skyrocket.de/img_sat/gsat-16__1.jpg",
    description: "GSAT-16 is a communication satellite launched by ISRO to provide services in telecommunication, television broadcasting, and satellite-based navigation. It was placed in a geostationary orbit and has a mission life of 12 years.",
    link: "https://en.wikipedia.org/wiki/GSAT-16",
    category: "Geostationary Orbit", // GSAT-16 operates in a geostationary orbit.
  },
  {
    id: 18,
    name: "Soyuz T-11",
    missionType: "Human Spaceflight",
    operator: "Soviet Space Program",
    launchDate: "3 April 1984",
    launchMass: "6,850 kg (15,100 lb)",
    power: "Solar arrays",
    launchVehicle: "Soyuz-U",
    launchSite: "Baikonur Cosmodrome",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Low Earth",
      periapsis: "215 km (134 mi)",
      apoapsis: "220 km (137 mi)",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Soyuz-T-11-Mission-Patch.svg",
    description: "Soyuz T-11 was a Soviet crewed spaceflight mission launched in 1984. The mission carried the first Indian astronaut, Rakesh Sharma, to space. The spacecraft docked with the Salyut 7 space station, where Sharma conducted scientific experiments and communicated with Indian Prime Minister Indira Gandhi.",
    link: "https://en.wikipedia.org/wiki/Soyuz_T-11",
    category: "Crewed spacecraft", // Soyuz T-11 was a crewed spacecraft mission.
  },
  {
    id: 19,
    name: "GSAT-6A",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "29 March 2018",
    launchMass: "2,140 kg (4,720 lb)",
    power: "3,000 watts",
    launchVehicle: "GSLV Mk II",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "83° East",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/GSAT-6A_Undergoing_Acoustic_Test.jpg/390px-GSAT-6A_Undergoing_Acoustic_Test.jpg",
    description: "GSAT-6A was a communication satellite launched by ISRO. The mission was deemed a failure after contact with the satellite was lost two days after launch. It was intended to provide mobile communication services through multi-beam coverage.",
    link: "https://en.wikipedia.org/wiki/GSAT-6A",
    category: "Mission failure", // The mission failed due to loss of communication with the satellite.
  },
  {
    id: 20,
    name: "Chandrayaan-2",
    missionType: "Lunar Exploration",
    operator: "ISRO",
    launchDate: "22 July 2019",
    launchMass: "3,850 kg (8,490 lb)",
    power: "1,000 watts",
    launchVehicle: "GSLV Mk III-M1",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Selenocentric",
      regime: "Lunar orbit",
      periapsis: "100 km (62 mi)",
      apoapsis: "100 km (62 mi)",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/GSLV_Mk_III_M1%2C_Chandrayaan-2_-_Vikram_lander_mounted_on_top_of_orbiter.jpg/390px-GSLV_Mk_III_M1%2C_Chandrayaan-2_-_Vikram_lander_mounted_on_top_of_orbiter.jpg",
    description: "Chandrayaan-2 is India's second lunar exploration mission, launched by ISRO. It consists of an orbiter, a lander named Vikram, and a rover named Pragyan. Although the lander failed during its descent, the orbiter continues to study the Moon's surface and exosphere.",
    link: "https://en.wikipedia.org/wiki/Chandrayaan-2",
    category: "Extra-terrestrial missions", // Chandrayaan-2 is a lunar exploration mission.
  },
  {
    id: 21,
    name: "GSAT-12",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "15 July 2011",
    launchMass: "1,410 kg (3,110 lb)",
    power: "1,350 watts",
    launchVehicle: "PSLV-C17",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geosynchronous",
      longitude: "83° East",
    },
    image: "https://admin.indiantelevision.com/sites/default/files/styles/medium_3/public/images/satellites-images/2016/05/06/Untitled-1.jpg?itok=_abxTAQv",
    description: "GSAT-12 is a communication satellite launched by ISRO, designed to replace INSAT-3B. It provides telecommunication, television broadcasting, and satellite-based navigation services in India. The satellite is placed in a geosynchronous orbit with a mission life of 8 years.",
    link: "https://en.wikipedia.org/wiki/GSAT-12",
    category: "Geosynchronous Orbit", // GSAT-12 operates in a geosynchronous orbit.
  },
  {
    id: 22,
    name: "GSAT-15",
    missionType: "Communication",
    operator: "ISRO",
    launchDate: "10 November 2015",
    launchMass: "3,164 kg (6,975 lb)",
    power: "6,000 watts",
    launchVehicle: "Ariane 5 ECA",
    launchSite: "Guiana Space Centre",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Geostationary",
      longitude: "93.5° East",
    },
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYxZKD8bpnJfKss-DCuUjtjpXZV7dFMG-EhA&usqp=CAU",
    description: "GSAT-15 is a communication satellite launched by ISRO to augment telecommunication, television broadcasting, and satellite-based navigation services. It was placed in a geostationary orbit and has a mission life of 12 years.",
    link: "https://en.wikipedia.org/wiki/GSAT-15",
    category: "Geostationary Orbit", // GSAT-15 operates in a geostationary orbit.
  },
  {
    id: 23,
    name: "Shenzhou 5",
    missionType: "Human Spaceflight",
    operator: "China National Space Administration (CNSA)",
    launchDate: "15 October 2003",
    launchMass: "7,840 kg (17,290 lb)",
    power: "Solar arrays",
    launchVehicle: "Long March 2F",
    launchSite: "Jiuquan Satellite Launch Center",
    orbit: {
      referenceSystem: "Geocentric",
      regime: "Low Earth",
      periapsis: "332 km (206 mi)",
      apoapsis: "336 km (209 mi)",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shenzhou-5_mockup_and_parachute_at_NMC.jpg/390px-Shenzhou-5_mockup_and_parachute_at_NMC.jpg",
    description: "Shenzhou 5 was China's first crewed space mission, launched by CNSA. It carried astronaut Yang Liwei into space, making China the third country to independently send a human into orbit. The mission lasted for 21 hours, completing 14 orbits around the Earth.",
    link: "https://en.wikipedia.org/wiki/Shenzhou_5",
    category: "Crewed spacecraft", // Shenzhou 5 was a crewed spacecraft mission.
  },
  {
    id: 24,
    name: "Vikram Lander (Chandrayaan-2)",
    missionType: "Lunar Exploration",
    operator: "ISRO",
    launchDate: "22 July 2019",
    launchMass: "1,471 kg (3,242 lb)",
    power: "650 watts",
    launchVehicle: "GSLV Mk III-M1",
    launchSite: "Satish Dhawan Space Centre",
    orbit: {
      referenceSystem: "Selenocentric",
      regime: "Lunar orbit",
      periapsis: "100 km (62 mi)",
      apoapsis: "100 km (62 mi)",
    },
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/GSLV_Mk_III_M1%2C_Chandrayaan-2_-_Pragyan_rover_mounted_on_the_ramp_of_Vikram_lander.jpg/330px-GSLV_Mk_III_M1%2C_Chandrayaan-2_-_Pragyan_rover_mounted_on_the_ramp_of_Vikram_lander.jpg",
    description: "The Vikram Lander, part of the Chandrayaan-2 mission, was intended to make a soft landing on the Moon's south pole. However, communication was lost during the final descent, resulting in a mission failure. The orbiter continues to function and send data.",
    link: "https://en.wikipedia.org/wiki/Chandrayaan-2#Vikram_lander",
    category: "Mission failure", // The Vikram Lander mission failed due to a communication loss during descent.
  },
  
  
  
];
